---

- name: Install dependencies
  hosts: all
  roles:
    - install_k3s
    - install_flux

- name: Run K3s service
  hosts: all
  roles:
    - role: run_k3s
      vars:
        k3s_registration_url: "https://{{ k3s_primary_ip }}:6443"

- name: Bootstrap flux
  hosts: all
  roles:
    - bootstrap_flux

- name: Configure secrets
  hosts: all
  roles:
    - configure_secrets
