apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 30m
  chart:
    spec:
      chart: ghost
      version: "19.3.x"
      sourceRef:
        kind: HelmRepository
        name: ghost
        namespace: ghost
  releaseName: ghost
  targetNamespace: ghost
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostname: gmarcha.com
      path: /blog
      tls: true
    existingSecret: ghost
    ghostUsername: admin
    ghostPassword: password
    ghostEmail: gmarcha@github.com
    ghostBlogTitle: gmarcha's blog
    ghostHost: gmarcha.com
    ghostPath: /blog
