---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vite-app
  namespace: vite-app
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: vite-app
    namespace: vite-app
  path: ./deploy
  prune: true
  wait: true
  timeout: 10m0s
